[package]
name = "yva"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.6", features = ["web"] }
serde = { version = "1.0", features = ["derive"] }
serde-saphyr = { git = "https://github.com/bourumir-wyngs/serde-saphyr.git", features = ["miette"] }
miette = { version = "7.6", features = ["fancy-no-syscall"] }
ansi-to-html = "0.2.1"
serde_json = "1.0"
